# -*- coding: utf-8 -*-
from __future__ import annotations

"""Catálogo embutido de fontes oficiais (entradas curadas)."""

from typing import List

from .base import CatalogEntry


def builtin_entries() -> List[CatalogEntry]:
    """Retorna a lista curada de entradas de fontes oficiais."""
    entries = [
        CatalogEntry(
            vendor="NVIDIA",
            model="GeForce",
            kinds=["gpu", "graphics", "display"],
            version="551.86",
            url="https://www.nvidia.com/download/index.aspx",
            official=True,
            signature="",
            checksums={},
            date="2026-08-14",
        ),
        CatalogEntry(
            vendor="AMD",
            model="Radeon Adrenalin",
            kinds=["gpu", "graphics", "display"],
            version="24.5.1",
            url="https://www.amd.com/en/support/download/drivers.html",
            official=True,
            signature="",
            checksums={},
            date="2026-08-02",
        ),
        CatalogEntry(
            vendor="Intel",
            model="Iris Xe / UHD Graphics",
            kinds=["gpu", "graphics", "display"],
            version="31.0.101.5594",
            url="https://www.intel.com/content/www/us/en/download-center/home.html",
            official=True,
            signature="",
            checksums={},
            date="2026-07-20",
        ),
        CatalogEntry(
            vendor="Realtek",
            model="HD Audio Codec",
            kinds=["audio", "sound"],
            version="6.0.9770.1",
            url="https://www.realtek.com/Download/List?cate_id=292",
            official=True,
            signature="",
            checksums={},
            date="2026-08-09",
        ),
        CatalogEntry(
            vendor="Realtek",
            model="Wi-Fi Adapter (RTL88x2)",
            kinds=["network", "wifi", "wireless"],
            version="6001.16.153",
            url="https://www.realtek.com/Download/List?cate_id=584",
            official=True,
            signature="",
            checksums={},
            date="2026-07-25",
        ),
        CatalogEntry(
            vendor="Intel",
            model="Wi-Fi 6 AX200",
            kinds=["network", "wifi", "wireless"],
            version="23.20.0.4",
            url="https://www.intel.com/content/www/us/en/download/19351/intel-wireless-wi-fi-drivers-for-windows-10-and-windows-11.html",
            official=True,
            signature="",
            checksums={},
            date="2026-08-11",
        ),
        CatalogEntry(
            vendor="Intel",
            model="Wi-Fi 6E AX210",
            kinds=["network", "wifi", "wireless"],
            version="23.20.0.4",
            url="https://www.intel.com/content/www/us/en/download/19351/intel-wireless-wi-fi-drivers-for-windows-10-and-windows-11.html",
            official=True,
            signature="",
            checksums={},
            date="2026-08-11",
        ),
        CatalogEntry(
            vendor="Broadcom",
            model="Wireless Network Adapter",
            kinds=["network", "wifi", "wireless"],
            version="6.30.223.271",
            url="https://www.broadcom.com/support/downloads",
            official=True,
            signature="",
            checksums={},
            date="2026-06-28",
        ),
        CatalogEntry(
            vendor="Intel",
            model="Wireless Bluetooth",
            kinds=["bluetooth", "network"],
            version="23.20.0.3",
            url="https://www.intel.com/content/www/us/en/download/18649/intel-wireless-bluetooth-for-windows-10-and-windows-11.html",
            official=True,
            signature="",
            checksums={},
            date="2026-08-11",
        ),
        CatalogEntry(
            vendor="Realtek",
            model="Bluetooth Adapter",
            kinds=["bluetooth", "network"],
            version="1.10.513.1",
            url="https://www.realtek.com/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software",
            official=True,
            signature="",
            checksums={},
            date="2026-07-19",
        ),
        CatalogEntry(
            vendor="Samsung",
            model="PCIe NVMe SSD",
            kinds=["storage", "nvme", "ssd"],
            version="3.4",
            url="https://semiconductor.samsung.com/consumer-storage/support/tools/",
            official=True,
            signature="",
            checksums={},
            date="2026-07-30",
        ),
        CatalogEntry(
            vendor="SanDisk",
            model="NVMe SSD",
            kinds=["storage", "nvme", "ssd"],
            version="3.2.0.3005",
            url="https://www.westerndigital.com/support/product-downloads",
            official=True,
            signature="",
            checksums={},
            date="2026-08-05",
        ),
        CatalogEntry(
            vendor="Synaptics",
            model="Touchpad",
            kinds=["input", "touchpad"],
            version="19.5.35.1",
            url="https://www.synaptics.com/",
            official=True,
            signature="",
            checksums={},
            date="2026-07-12",
        ),
        CatalogEntry(
            vendor="ELAN",
            model="Touchscreen / Touchpad",
            kinds=["input", "touchpad", "touchscreen"],
            version="16.0.0.15",
            url="https://www.elan-touch.com/",
            official=True,
            signature="",
            checksums={},
            date="2026-07-08",
        ),
        CatalogEntry(
            vendor="MediaTek",
            model="Wi-Fi Adapter (MT7921)",
            kinds=["network", "wifi", "wireless"],
            version="3.3.0.1180",
            url="https://www.mediatek.com/products/networking-and-connectivity/wifi-6e/mediatek-fillogic-821",
            official=True,
            signature="",
            checksums={},
            date="2026-06-18",
        ),
        CatalogEntry(
            vendor="Qualcomm Atheros",
            model="Wireless Adapter",
            kinds=["network", "wifi", "wireless"],
            version="12.0.0.914",
            url="https://support.qualcomm.com/",
            official=True,
            signature="",
            checksums={},
            date="2026-07-27",
        ),
        CatalogEntry(
            vendor="TP-Link",
            model="USB Wi-Fi Adapter (Archer)",
            kinds=["network", "wifi", "adapter"],
            version="11.0.0.1122",
            url="https://www.tp-link.com/us/support/download-center/",
            official=True,
            signature="",
            checksums={},
            date="2026-08-01",
        ),
    ]
    return entries